@startuml





/' Objects '/

class Callback {
	+Callback()
	+~Callback()
	+operator<<(std::ostream& ostr, const Callback::SharedPtr& cb) : std :: ostream&
	-mMessages : std::map<Key_t, Message_t>
	-mMutex : std::mutex
	+getFirst(const Receipt& receipt, Type type) : std::optional<Message_t>
	+waitFirst(const Receipt& receipt, Type type) : std::optional<Message_t>
	+clear() : void
	+notify(TaskId taskId, Type type, const std::string& message) : void
}


class Receipt {
	+Receipt(Mode mode)
	+getEndTime() : ChronotTime_t& {query}
	+getStartTime() : ChronotTime_t& {query}
	-mMode : Mode
	-mStatus : Status
	+getTaskId() : TaskId {query}
	+getExecutionMode() : int {query}
	+getStatus() : int {query}
	-mEndTime : time_point<std::chrono::system_clock>
	-mStartTime : time_point<std::chrono::system_clock>
	-mTaskId : uint32_t
	+setEndTime() : void
	+setStatus(Status status) : void
}


enum Callback::Type {
	NOTIFICATION
	RESULT
}


enum Receipt::Mode {
	Async
	Blocking
}


enum Receipt::Status {
	FAIL
	OK
}


class Callback::Message_t {
	+mTime : Receipt::ChronotTime_t
	+mResult : std::string
}


class scoped_logger {
	+scoped_logger(const std::string& className, const char* funcName, unsigned line)
	+~scoped_logger()
	-_ss : std::stringstream
	+stream() : std::stringstream&
}


namespace Cmder {
	class Agent {
		-Agent(Server& server, Callback::SharedPtr callback)
		+~Agent()
		-mCallback : Callback::SharedPtr
		+doTask(Receipt::Mode mode, const TaskName& task, std::string& result) : Receipt {query}
		-mServer : Server&
		+{static} create(Server& server, Callback::SharedPtr callback) : SharedPtr
		+getStatus() : Status {query}
		-mStatus : Status
		-mMutex : mutable std::mutex
		-mConditionVariable : std::condition_variable
		-mNotifications : std::queue<std::string>
		-mDebugName : std::string
		+getName() : std::string& {query}
		-mThreadPtr : std::unique_ptr<std::thread>
		+statNotification(const std::string& notificationName) : uint64_t {query}
		+notify(const std::string& message) : void
		+registerAgent() : void
		-run() : void
		+start() : void
		+stop() : void
		+unregisterAgent() : void
	}

	abstract class IControllableThread {
		+{abstract} getStatus() : int {query}
		+{abstract} start() : void
		+{abstract} stop() : void
	}

	abstract class IStatProvider {
		+{abstract} statNotification(const std::string& notificationName) : uint64_t {query}
	}

	class Server {
		+Server()
		+~Server()
		+getStatus() : Cmder::Status {query}
		-mStatus : Status
		-mMutex : mutable std::mutex
		-mConditionVariable : std::condition_variable
		-mNotificationStatistics : std::map<std::string, uint64_t>
		-mThreadPtr : std::unique_ptr<std::thread>
		+statNotification(const std::string& notificationName) : uint64_t {query}
		-mAgents : vector<Agent::WeakPtr>
		+registerAgent(Agent::SharedPtr agent) : void
		-run() : void
		+start() : void
		+stop() : void
		+unregister(const std::string agentName) : void
	}

	class Task {
		-mTaskConfiguration : std::vector<TaskConfig>
	}

	enum Status {
		Init
		Run
		Start
		Stop
	}

	enum TaskName {
		BlockMe_3s
		Pi
		PingMe_5x
	}

	class Task::TaskConfig {
	}

	namespace Testing {
		class AgentTest {
			#{static} sAsyncAgent : static Agent::SharedPtr
			#{static} sNoCallbackAgent : static Agent::SharedPtr
			#{static} sCallback : static Callback::SharedPtr
			#{static} sServer : static Server
			#SetUp() : void
			#{static} SetUpTestSuite() : void
			#{static} TearDownTestSuite() : void
		}

		class ServerTest {
			#mServer : std::unique_ptr<Server>
			#SetUp() : void
			#{static} SetUpTestSuite() : void
			#TearDown() : void
			#{static} TearDownTestSuite() : void
		}
	}
}





/' Inheritance relationships '/

Cmder.IControllableThread <|-- Cmder.Agent


Cmder.IControllableThread <|-- Cmder.Server


Cmder.IStatProvider <|-- Cmder.Server





/' Aggregation relationships '/

Cmder.Agent *-- .Callback


Cmder.Agent *-- Cmder.Server


Cmder.Agent *-- Cmder.Status


Cmder.Testing.AgentTest "2" *-- Cmder.Agent


Cmder.Testing.AgentTest *-- .Callback


Cmder.Testing.AgentTest *-- Cmder.Server


.Callback::Message_t *-- .Receipt


.Receipt *-- Cmder.Status


Cmder.Server *-- Cmder.Agent


Cmder.Server *-- Cmder.Status


Cmder.Testing.ServerTest *-- Cmder.Server






/' Nested objects '/

.Callback +-- .Callback::Message_t


.Callback +-- .Callback::Type


.Receipt +-- .Receipt::Mode


.Receipt +-- .Receipt::Status


Cmder.Task +-- Cmder.Task::TaskConfig




@enduml
